/*
 *
 * MoviesPage constants
 *
 */

export const DEFAULT_ACTION = 'app/MoviesPage/DEFAULT_ACTION';

export const FETCHING_MOVIES_ACTION = 'app/MoviesPage/FETCHING_MOVIES_ACTION';
export const FETCHING_MOVIES_SUCCESS_ACTION =
  'app/MoviesPage/FETCHING_MOVIES_SUCCESS_ACTION';
export const FETCHING_MOVIES_FAILED_ACTION =
  'app/MoviesPage/FETCHING_MOVIES_FAILED_ACTION';

export const SEARCH_MOVIE_BY_NAME_ACTION =
  'app/MoviesPage/SEARCH_MOVIE_BY_NAME_ACTION';
export const SEARCH_MOVIE_BY_NAME_SUCCESS_ACTION =
  'app/MoviesPage/SEARCH_MOVIE_BY_NAME_SUCCESS_ACTION';
export const SEARCH_MOVIE_BY_NAME_FAILED_ACTION =
  'app/MoviesPage/SEARCH_MOVIE_BY_NAME_FAILED_ACTION';
