/*
 *
 * App constants
 *
 */

export const FETCH_MOVIES_ACTION = 'app/App/FETCH_MOVIES_ACTION';

export const FETCH_MOVIES_SUCCESS_ACTION =
  'app/App/FETCH_MOVIES_SUCCESS_ACTION';

export const FETCH_MOVIES_FAILED_ACTION = 'app/App/FETCH_MOVIES_FAILED_ACTION';
