/*
 *
 * App constants
 *
 */

export const FETCH_MOVIES_ACTION = 'app/App/FETCH_MOVIES_ACTION';

export const FETCH_HOT_MOVIES_SUCCESS_ACTION =
  'app/App/FETCH_HOT_MOVIES_SUCCESS_ACTION';
export const FETCH_HOT_MOVIES_FAILED_ACTION =
  'app/App/FETCH_HOT_MOVIES_FAILED_ACTION';

export const FETCH_LATEST_MOVIES_SUCCESS_ACTION =
  'app/App/FETCH_LATEST_MOVIES_SUCCESS_ACTION';
export const FETCH_LATEST_MOVIES_FAILED_ACTION =
  'app/App/FETCH_LATEST_MOVIES_FAILED_ACTION';

export const AUTHORIZE_USER_ACTION = 'app/App/AUTHORIZE_USER_ACTION';
export const AUTHORIZE_USER_SUCCESS_ACTION =
  'app/App/AUTHORIZE_USER_SUCCESS_ACTION';
export const AUTHORIZE_USER_FAILED_ACTION =
  'app/App/AUTHORIZE_USER_FAILED_ACTION';

export const SIGN_OUT_ACTION = 'app/App/SIGN_OUT_ACTION';
